
#* zemlje
#?svaka zemlja ima 10 stvari za pratiti:
#?ime, cijena, cijenaKuce, renta, 1kuca, 2kuca, 3kuca, 4kuca, hotel i vlasnika
#?cijena će uvjek bit ponuđena osim ako vlasnik nije None, cijenaKuce je univerzalna kolko ce kuce doci, 
#?sve cjene koje se daju drugima tj. renta,1kuca...hotel imaju True/False da se lakse nade tj. trazit ce se koji je True i onda nabit cijena
mediterranean_ave = {"ime":"Mediterranean avenue",
                     "cijena":60,
                     "cijenaKuce":50,
                     "renta":[False,2],
                     "1kuca":[False,10],
                     "2kuca":[False,30],
                     "3kuca":[False,90],
                     "4kuca":[False,160],
                     "hotel":[False,250],
                     "vlasnik":None}
baltic_ave = {"ime":"Baltic avenue",
                    "cijena":60,
                     "cijenaKuce":50,
                     "renta":[False,4],
                     "1kuca":[False,20],
                     "2kuca":[False,60],
                     "3kuca":[False,180],
                     "4kuca":[False,320],
                     "hotel":[False,450],
                     "vlasnik":None}
oriental_ave = {"ime":"Oriental avenue",
                    "cijena":100,
                    "cijenaKuce":50,
                     "renta":[False,6],
                     "1kuca":[False,30],
                     "2kuca":[False,90],
                     "3kuca":[False,270],
                     "4kuca":[False,400],
                     "hotel":[False,550],
                     "vlasnik":None}
vermont_ave = {"ime":"Vermont avenue",
                    "cijena":100,
                     "cijenaKuce":50,
                     "renta":[False,6],
                     "1kuca":[False,30],
                     "2kuca":[False,90],
                     "3kuca":[False,270],
                     "4kuca":[False,400],
                     "hotel":[False,550],
                     "vlasnik":None}
connecticut_ave = {"ime":"Connecticut avenue",
                    "cijena":120,
                     "cijenaKuce":50,
                     "renta":[False,8],
                     "1kuca":[False,40],
                     "2kuca":[False,100],
                     "3kuca":[False,300],
                     "4kuca":[False,450],
                     "hotel":[False,600],
                     "vlasnik":None}
st_charles = {"ime":"St. Charles place",
                    "cijena":140,
                     "cijenaKuce":100,
                     "renta":[False,10],
                     "1kuca":[False,50],
                     "2kuca":[False,150],
                     "3kuca":[False,450],
                     "4kuca":[False,625],
                     "hotel":[False,750],
                     "vlasnik":None}
states_ave = {"ime":"States avenue",
                    "cijena":140,
                     "cijenaKuce":100,
                     "renta":[False,10],
                     "1kuca":[False,50],
                     "2kuca":[False,150],
                     "3kuca":[False,450],
                     "4kuca":[False,625],
                     "hotel":[False,750],
                     "vlasnik":None}
virginia_ave = {"ime":"Virginia avenue",
                     "cijena":160,
                     "cijenaKuce":100,
                     "renta":[False,12],
                     "1kuca":[False,60],
                     "2kuca":[False,180],
                     "3kuca":[False,500],
                     "4kuca":[False,700],
                     "hotel":[False,900],
                     "vlasnik":None}
st_james = {"ime":"St. James place",
                    "cijena":180,
                     "cijenaKuce":100,
                     "renta":[False,14],
                     "1kuca":[False,70],
                     "2kuca":[False,200],
                     "3kuca":[False,550],
                     "4kuca":[False,750],
                     "hotel":[False,950],
                     "vlasnik":None}
tennessee_ave = {"ime":"Tennessee avenue",
                    "cijena":180,
                     "cijenaKuce":100,
                     "renta":[False,14],
                     "1kuca":[False,70],
                     "2kuca":[False,200],
                     "3kuca":[False,550],
                     "4kuca":[False,750],
                     "hotel":[False,950],
                     "vlasnik":None}
newyork_ave = {"ime":"New York avenue",
                    "cijena":200,
                     "cijenaKuce":100,
                     "renta":[False,16],
                     "1kuca":[False,80],
                     "2kuca":[False,220],
                     "3kuca":[False,600],
                     "4kuca":[False,800],
                     "hotel":[False,1000],
                     "vlasnik":None}
kentucky_ave = {"ime":"Kentucky avenue",
                    "cijena":220,
                     "cijenaKuce":150,
                     "renta":[False,18],
                     "1kuca":[False,90],
                     "2kuca":[False,250],
                     "3kuca":[False,700],
                     "4kuca":[False,875],
                     "hotel":[False,1050],
                     "vlasnik":None}
indiana_ave = {"ime":"Indiana avenue",
                    "cijena":220,
                     "cijenaKuce":150,
                     "renta":[False,18],
                     "1kuca":[False,90],
                     "2kuca":[False,250],
                     "3kuca":[False,700],
                     "4kuca":[False,875],
                     "hotel":[False,1050],
                     "vlasnik":None}
illinois_ave = {"ime":"Illinois avenue"
                    ,"cijena":240,
                     "cijenaKuce":150,
                     "renta":[False,20],
                     "1kuca":[False,100],
                     "2kuca":[False,300],
                     "3kuca":[False,750],
                     "4kuca":[False,925],
                     "hotel":[False,1100],
                     "vlasnik":None}
atlantic_ave = {"ime":"Atlantic avenue",
                    "cijena":260,
                     "cijenaKuce":150,
                     "renta":[False,22],
                     "1kuca":[False,110],
                     "2kuca":[False,330],
                     "3kuca":[False,800],
                     "4kuca":[False,975],
                     "hotel":[False,1150],
                     "vlasnik":None}
ventor_ave = {"ime":"Ventor avenue",
                    "cijena":260,
                     "cijenaKuce":150,
                     "renta":[False,22],
                     "1kuca":[False,110],
                     "2kuca":[False,330],
                     "3kuca":[False,800],
                     "4kuca":[False,975],
                     "hotel":[False,1150],
                     "vlasnik":None}
marvin_gardens = {"ime":"Marvin gardens",
                    "cijena":280,
                     "cijenaKuce":150,
                     "renta":[False,24],
                     "1kuca":[False,120],
                     "2kuca":[False,360],
                     "3kuca":[False,850],
                     "4kuca":[False,1025],
                     "hotel":[False,1200],
                     "vlasnik":None}
pacific_ave = {"ime":"Pacific avenue",
                    "cijena":300,
                     "cijenaKuce":200,
                     "renta":[False,26],
                     "1kuca":[False,130],
                     "2kuca":[False,390],
                     "3kuca":[False,900],
                     "4kuca":[False,1100],
                     "hotel":[False,1275],
                     "vlasnik":None}
northcarolina_ave = {"ime":"North Carolina avenue",
                    "cijena":300,
                     "cijenaKuce":200,
                     "renta":[False,26],
                     "1kuca":[False,130],
                     "2kuca":[False,390],
                     "3kuca":[False,900],
                     "4kuca":[False,1100],
                     "hotel":[False,1275],
                     "vlasnik":None}
pennsylvania_ave = {"ime":"Pennsylvania avenue",
                    "cijena":320,
                     "cijenaKuce":200,
                     "renta":[False,28],
                     "1kuca":[False,150],
                     "2kuca":[False,450],
                     "3kuca":[False,1000],
                     "4kuca":[False,1200],
                     "hotel":[False,1400],
                     "vlasnik":None}
park_palace = {"ime":"Park place",
                    "cijena":350,
                     "cijenaKuce":200,
                     "renta":[False,35],
                     "1kuca":[False,175],
                     "2kuca":[False,500],
                     "3kuca":[False,1100],
                     "4kuca":[False,1300],
                     "hotel":[False,1500],
                     "vlasnik":None}
boardwalk = {"ime": "Boardwalk",
                    "cijena":400,
                     "cijenaKuce":200,
                     "renta":[False,50],
                     "1kuca":[False,200],
                     "2kuca":[False,600],
                     "3kuca":[False,1400],
                     "4kuca":[False,1700],
                     "hotel":[False,2000],
                     "vlasnik":None}
#* kolodvori
#?skoro isto ko zemlje samo što prati cjenu, rentu i vlasnika
#?svaki dodatni tko netko posjeduje ce biti +25 na renti, najlakše je da samo tražimo tko sve što ima i onda pozbrajamo rente
reading_rail = {"ime":"Reading railroad",
                "cijena":200,
                "renta":[True,25],
                "vlasnik":None}
pennsylvania_rail = {"ime":"Pennsylvania railroad",
                    "cijena":200,
                    "renta":[True,25],
                    "vlasnik":None}
bo_rail = {"ime":"B&O railroad",
                "cijena":200,
                "renta":[True,25],
                "vlasnik":None}
short_rail = {"ime":"Short line",
              "cijena":200,
                "renta":[True,25],
                "vlasnik":None}
#* utils
#?samo cijena i vlasnik
#!način rada je sjeban jer ako imas 1 onda ce renta biti vrijednos dice*4, ako dva onda je vrijednost dice*10
electric = {"ime":"Electric company",
            "cijena":150,
            "vlasnik":None}
water = {"ime":"Water works",
            "cijena":150,
            "vlasnik":None}
#* nonbuy stvari i ostala polja
#?sve što počinje na nonbuy se nemre kupit jer je to dobar način za bugproof i to je uvijek na index[0]
#?svaki će biti lista koja na index[1] ima string koji može služizi za aktiviranje funkcija
start = ["nonbuy","takeStart"]
tax = ["nonbuy","tax"]
luxtax = ["nonbuy","luxtax"]
comm_chest = ["nonbuy","pickComm"]
chance = ["nonbuy","pickChance"]
jail = ["nonbuy","jailCheck"]
goto_jail = ["nonbuy","gotoJail"]
parking = ["nonbuy","parkingCheck"]
#* lista svih polja
polja = [start,
         mediterranean_ave,
         comm_chest,baltic_ave,
         tax,
         reading_rail,
         oriental_ave,
         chance,
         vermont_ave,
         connecticut_ave,
         jail,
         st_charles,
         electric,
         states_ave,
         virginia_ave,
         pennsylvania_rail,
         st_james,
         comm_chest,
         tennessee_ave,
         newyork_ave,
         parking,
         kentucky_ave,
         chance,
         indiana_ave,
         illinois_ave,
         bo_rail,
         atlantic_ave,
         ventor_ave,
         water,
         marvin_gardens,
         goto_jail,
         pacific_ave,
         northcarolina_ave,
         comm_chest,
         pennsylvania_ave,
         short_rail,
         chance,
         park_palace,
         luxtax,
         boardwalk
         ]
#* test funkcija
#? služi da ti pokaže ako se file spojio i treba printat sva polja
def test_fn():
    print(*polja)